apiVersion: v1
kind: ConfigMap
metadata:
  namespace: tick
  name: "telegraf-infra"
data:
  telegraf.conf: |+
    [agent]
      interval = "30s"
      round_interval = true
      metric_batch_size = 1000
      metric_buffer_limit = 10000
      collection_jitter = "0s"
      flush_interval = "10s"
      flush_jitter = "0s"
      precision = ""
      debug = true
      quiet = false
      logfile = ""
      hostname = "telegraf"
      omit_hostname = false

    [[outputs.influxdb]]
      urls = ["http://influxdb.tick.svc.cluster.local:8086"]
      database = "telegraf"
      retention_policy = "rp_90d"
      write_consistency = "any"
      timeout = "5s"
      username = "dbUser"
      password = "dbPassword"
      user_agent = "telegraf"
      insecure_skip_verify = false

    [[inputs.http_listener]]
      service_address = ":8186"

    [[inputs.socket_listener]]
      service_address = "udp://:8092"
      data_format = "influx"

    [[inputs.http_response]]
      address = "https://www.google.fr"
      method = "GET"
       # HTTP/HTTPS request given an address a method and a timeout

---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: tick
  name: telegraf-deployment
  labels:
    app: telegraf
spec:
  selector:
    matchLabels:
      app: telegraf
  template:
    metadata:
      labels:
        app: telegraf 
    spec:
      containers:
        - name: telegraf
          image: telegraf
          ports:
          - name: udp
            protocol: UDP
            containerPort: 8092
          - name: http
            containerPort: 8186
          volumeMounts:
          - name: config
            mountPath: /etc/telegraf
      volumes:
      - name: config
        configMap:
          name: telegraf-infra
